package com.neoprojectmanager.model;

import static org.apache.commons.lang.StringUtils.isBlank;

import java.util.Iterator;

import org.apache.commons.lang.NotImplementedException;
import org.neo4j.graphdb.Direction;
import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.graphdb.Node;
import org.neo4j.graphdb.Relationship;
import org.neo4j.graphdb.RelationshipType;
import org.neo4j.graphdb.Transaction;
import org.neo4j.kernel.EmbeddedGraphDatabase;

/**
 * The factory is used to generate all the first-level domain model objects.
 * Projects, for example, as a project can exist indipendently from other
 * objects. A Task should be generated by a Project instead, as a Task should
 * alsais belogn to a project. It evnelops the db instance we are actually
 * working on. And allow to manage in one location only the inizialization of
 * those objects.
 * 
 * @author xan
 * 
 */
public class Factory {
	enum RELATIONSHIP implements RelationshipType {
		PROJECTS, RESOURCES
	}

	private GraphDatabaseService gdbs = null;
	private String dbFolder = null;

	public Factory(String dbFolder) {
		this.dbFolder = dbFolder;
		if (gdbs == null)
			this.gdbs = new EmbeddedGraphDatabase(this.dbFolder);
	}

	public Iterator<Project> getAllProjects() {
		return new Iterator<Project>() {
			private final Iterator<Relationship> iterator = gdbs
					.getReferenceNode().getRelationships(RELATIONSHIP.PROJECTS,
							Direction.OUTGOING).iterator();

			public boolean hasNext() {
				return iterator.hasNext();
			}

			public Project next() {
				Node nextNode = iterator.next().getEndNode();
				return new Project(nextNode, gdbs);
			}

			public void remove() {
				throw new NotImplementedException("This method is not implemented.");
			}
		};
	}

	/**
	 * shutdown the database.
	 */
	public void close() {
		this.gdbs.shutdown();
		this.gdbs = null;
	}

	public Project createProject(String name) {
		if (isBlank(name))
			throw new IllegalArgumentException("Name can not be blank");
		Transaction tx = this.gdbs.beginTx();
		try {
			Project n = new Project(name, this.gdbs);
			tx.success();
			return n;
		} finally {
			tx.finish();
		}
	}

	public Resource createResource(String name) {
		if (isBlank(name))
			throw new IllegalArgumentException("Name can not be blank");
		Transaction tx = this.gdbs.beginTx();
		try {
			Resource r = new Resource(name, this.gdbs);
			tx.success();
			return r;
		} finally {
			tx.finish();
		}
	}

	public Project getProjectById(long id) {
		Transaction tx = this.gdbs.beginTx();
		try {
			Project p = new Project(this.gdbs.getNodeById(id), this.gdbs);
			tx.success();
			return p;
		} finally {
			tx.finish();
		}
	}

	public void clearDB() {
		Transaction tx = gdbs.beginTx();
		try {
			for (Node n : gdbs.getAllNodes()) {
				for (Relationship r : n.getRelationships()) {
					r.delete();
				}
				n.delete();
			}
			tx.success();
		} finally {
			tx.finish();
		}
	}

	public Transaction beginTx() {
		return gdbs.beginTx();
	}

	public void populateDB() {
		Transaction tx = gdbs.beginTx();
		try {
			Project project1 = createProject("Project 1");
			Task task1 = project1.createTask("TaskImpl 1");
			Task task2 = project1.createTask("TaskImpl 2");
			task1.setDurationInMinutes(60 * 24 * 10);
			task2.setDurationInMinutes(60 * 24 * 6);
			task2.addDependentOn(task1);
			tx.success();
		} finally {
			tx.finish();
		}
	}

	public String getDbFolder() {
		return dbFolder;
	}
}
